from pathlib import Path
from playwright.sync_api import sync_playwright, expect
import json, os, sys
sys.stdout.reconfigure(encoding='utf-8')
BASE=os.environ.get('AQUAWATCH_URL','http://127.0.0.1:3000')
OUT=Path(__file__).resolve().parents[1] / 'qa-artifacts'; OUT.mkdir(parents=True,exist_ok=True)
VIEWS={'overview':'Наблюдение за водой','map':'Карта миссии','devices':'Ваш флот','missions':'Миссии','analytics':'Измерения и отчёты','manual':'Ручное управление','journal':'Журнал событий','service':'Обслуживание','settings':'Настройки показателей','profile':'Профиль'}
with sync_playwright() as p:
    browser=p.chromium.launch(headless=True,args=['--renderer-process-limit=1','--disable-extensions','--js-flags=--max-old-space-size=128'])
    page=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True)
    errors=[]; results=[]
    page.on('pageerror',lambda e:errors.append(str(e)))
    def nav(view):
        page.evaluate('(v)=>location.hash=v',view)
        page.get_by_role('heading',name=VIEWS[view],exact=True).first.wait_for(timeout=30000)
        page.wait_for_load_state('networkidle')
    def record(name):
        results.append(name); print('PASS '+name,flush=True)
    def fleet():return page.evaluate('JSON.parse(localStorage.getItem("aquawatch.fleet.v2"))')
    try:
        page.goto(BASE,wait_until='networkidle',timeout=180000)
        page.get_by_role('heading',name=VIEWS['overview'],exact=True).wait_for(timeout=30000)
        page.get_by_role('button',name='Пауза симуляции',exact=True).click()
        record('overview loads')
        for view in VIEWS:
            nav(view)
            assert not page.evaluate('document.documentElement.scrollWidth>innerWidth'), view+' desktop overflow'
            if view in ['map','devices','analytics','manual']:
                page.screenshot(path=str(OUT/(view+'-desktop.png')),full_page=True)
        record('all 10 desktop sections without overflow')
        nav('devices')
        page.get_by_role('button',name='Добавить аппарат',exact=True).click()
        page.get_by_label('Имя робота').fill('QA SuBulaq')
        page.get_by_label('Модель',exact=True).fill('SB-TEST')
        page.get_by_label('Серийный номер').fill('QA-UNIQUE-2026')
        page.get_by_role('button',name='Добавить в демофлот',exact=True).click()
        page.get_by_label('Поиск аппарата').fill('QA-UNIQUE')
        expect(page.locator('.device-overview-card')).to_have_count(1)
        record('device registration and search')
        page.reload(wait_until='networkidle')
        expect(page.get_by_role('heading',name='QA SuBulaq',exact=True)).to_be_visible()
        record('fleet persists after reload')
        nav('profile')
        page.get_by_label('Имя',exact=True).fill('QA Оператор')
        page.get_by_label('Email',exact=True).fill('qa@example.test')
        page.get_by_role('button',name='Сохранить профиль').click()
        nav('overview');nav('profile')
        expect(page.get_by_label('Имя',exact=True)).to_have_value('QA Оператор')
        record('profile save and restore')
        nav('settings')
        numeric=page.locator('input[type=number]').first
        numeric.fill('99')
        expect(page.get_by_role('alert')).to_be_visible()
        expect(page.get_by_role('button',name='Сохранить изменения')).to_be_disabled()
        page.get_by_role('button',name='Сбросить',exact=True).click()
        expect(page.get_by_role('alert')).to_have_count(0)
        record('invalid thresholds rejected, reset works')
        nav('analytics')
        with page.expect_download() as download:
            page.get_by_role('button',name='Скачать CSV',exact=True).click()
        downloaded=download.value
        downloaded.save_as(str(OUT/'report.csv'))
        assert 'demo_simulation' in (OUT/'report.csv').read_text(encoding='utf-8-sig')
        page.locator('#report-device').click()
        page.get_by_role('option',name='QA SuBulaq',exact=True).click()
        expect(page.get_by_role('button',name='Скачать CSV',exact=True)).to_be_disabled()
        page.locator('#report-device').click();page.get_by_role('option',name='Все аппараты',exact=True).click()
        page.locator('#report-from').fill('2027-01-01')
        expect(page.get_by_role('button',name='Скачать CSV',exact=True)).to_be_disabled()
        record('CSV export, device filter and invalid date range')
        nav('map')
        page.get_by_role('button',name='Планировать маршрут').click()
        page.get_by_role('button',name='Готовый маршрут').click()
        expect(page.get_by_role('button',name='Удалить точку',exact=False)).to_have_count(3)
        page.screenshot(path=str(OUT/'map-editor-desktop.png'),full_page=True)
        record('route editor preset and panel')
        nav('manual')
        page.get_by_label('Выбрать аппарат').select_option(label='QA SuBulaq')
        if page.get_by_role('button',name='Продолжить симуляцию',exact=True).count():page.get_by_role('button',name='Продолжить симуляцию',exact=True).click()
        page.get_by_role('button',name='Включить управление').click()
        before=next(r for r in fleet() if r['name']=='QA SuBulaq')['position']
        forward=page.get_by_role('button',name='Вперёд',exact=True)
        forward.focus();page.keyboard.down('Space');page.wait_for_timeout(700);page.keyboard.up('Space');page.wait_for_timeout(250)
        moved=next(r for r in fleet() if r['name']=='QA SuBulaq')
        assert moved['position']!=before and moved['speed']==0
        page.get_by_role('button',name='Проверить потерю связи').click()
        expect(forward).to_be_disabled()
        page.get_by_role('button',name='Восстановить демосвязь').click()
        page.get_by_role('button',name='Добавить демопробу').click()
        record('manual motion, release stop, link loss and sample')
        nav('service')
        page.get_by_label('Результат проверки').fill('QA: проверка эталонным раствором')
        page.get_by_role('button',name='Сохранить калибровку').click()
        expect(page.get_by_text('QA: проверка эталонным раствором',exact=True)).to_be_visible()
        record('calibration journal')
        nav('journal');page.get_by_role('button',name='Прочитать все').click()
        record('notification read action')
        page.wait_for_timeout(5000)
        page.set_viewport_size({'width':390,'height':844})
        for view in VIEWS:
            nav(view)
            page.screenshot(path=str(OUT/(view+'-mobile.png')),full_page=True)
            assert not page.evaluate('document.documentElement.scrollWidth>innerWidth'),view+' mobile overflow'
        record('all 10 mobile sections without overflow')
        nav('overview')
        page.get_by_role('button',name='Открыть навигацию',exact=True).click()
        page.get_by_role('button',name='Флот',exact=False).first.click()
        expect(page.get_by_role('heading',name='Ваш флот',exact=True)).to_be_visible()
        assert not page.locator('[data-mobile=true]').is_visible()
        record('mobile navigation closes after selection')
        assert not errors,errors
        record('no browser page errors')
    finally:
        (OUT/'browser-results.json').write_text(json.dumps({'passed':results,'errors':errors},ensure_ascii=False,indent=2),encoding='utf-8')
        browser.close()
